### ISSUE TITLE
Popups only close on cancel

### ISSUE THREAD

**Issue by flekschas** [hms-dbmi/higlass#10]
_Commit_: fb2d74a16847e116c25b9608f0d6964f72223254

#### Steps to reproduce
1. Click on the plus icon
2. Try to close it with the _x_ button or an outside click

#### Observed behavior
- Does not close on either a click on the _x_ button or outside of the popup

![jan -22-2017 17-13-37](https://cloud.githubusercontent.com/assets/932103/22186617/548cc524-e0c6-11e6-880a-6aa3693846cd.gif)

#### Expected behavior
- Should close when clicking the _x_ button or outside of the popup

**Comment by pkerpedjiev** [comment]
Should be fixed in recent releases.
