### ISSUE TITLE
Why are there so many unevenly spaced tick marks on the heatmap legend?

### ISSUE THREAD

**Issue by flekschas** [hms-dbmi/higlass#112]
_Commit_: v0.7.3

#### Steps to reproduce
1. Open HiGlass.io
2. 🙄

#### Observed behavior
- Many unevenly spaced pronounced tickmarks are drawn next to the heatmap legend

<img width="662" alt="screen shot 2017-05-23 at 4 11 34 pm" src="https://cloud.githubusercontent.com/assets/932103/26374710/4b61312a-3fd4-11e7-9b96-777498dd0eba.png">

#### Expected behavior
- Maybe less tick marks and only min, max plus 50% values? Just curious why so many

**Comment by pkerpedjiev** [comment]
Because it's log scaled. Tick marks are drawn using D3's default ticks function: https://github.com/d3/d3-array/blob/master/README.md#ticks
