### ISSUE TITLE
Make chromosome labels configurable

### ISSUE THREAD

**Issue by pkerpedjiev** [hms-dbmi/higlass#113]
Should be possible to pass in a chromSizes file to configure the chromosome labels track:

This:

```
          {
            "chromInfoPath": "//s3.amazonaws.com/pkerp/data/hg19/chromSizes.tsv",
            "type": "horizontal-chromosome-labels",
            "position": "top",
            "name": "Chromosome Labels (hg19)",
            "height": 30,
            "uid": "I1QUF22JQJuJ38j9PS4iqw",
            "options": {}
          }
```

Should become:

```
          {
            "chromInfoPath": "//s3.amazonaws.com/pkerp/data/hg19/chromSizes.tsv",
            "type": "horizontal-chromosome-labels",
            "position": "top",
            "name": "Chromosome Labels",
            "source": "http://someurl.org/chromSizes.tsv",
            "height": 30,
            "uid": "I1QUF22JQJuJ38j9PS4iqw",
            "options": {}
          }
```

**Comment by rdacemel** [comment]
Nice web tool, please notify when you have this upgrade ready, it would be awesome!!
Thanks.

**Comment by pkerpedjiev** [comment]
Should work now. Chromosome sizes can also be added as tilesets in the higlass server.

**Comment by rdacemel** [comment]
Is this option available from the latest docker container? If so, how can I import the chromInfo file as a tileset? 

Thanks!!

**Comment by aakashsur** [comment]
Just to follow-up on this, what exactly would the ingest command for chromosome labels?

**Comment by pkerpedjiev** [comment]
Same as with other datatypes, just use `chromsizes` as the datatype and `chromsizes-tsv` as the filetype. If you want to be able to use them to search the genome make sure you add `coordSystem` (e.g. `mm9`).

**Comment by aakashsur** [comment]
Gotcha, so something like this: 

docker exec higlass-container python higlass-server/manage.py \
  ingest_tileset \
  --filename /tmp/chromsizes.tsv \
  --filetype chromsizes-tsv \
  --datatype chromsizes \
  --coordSystem mm9 \
  --name "mm9 Chromosome Labels"

Also, I saw a separate enhancement issue open about customizing assemblies, is loading the genomes of other organisms still on the todo list? (We are working on leishmania and trypanosomes)

**Comment by pkerpedjiev** [comment]
Yeah, that should work. Adding other genomes is a work in progress. If you want, maybe open an issue for the genome you're interested in and we can continue the conversation there.
