### ISSUE TITLE
Menu doesn't close on outer click after blurring the view

### ISSUE THREAD

**Issue by flekschas** [hms-dbmi/higlass#115]
_Commit_: v0.8.2

#### Steps to reproduce
1. Open the context menu
2. Switch to another app window with CMD+TAB

#### Observed behavior
- The opened menu stays visible and does not close anymore

Example: during the short pause over the button after opening the context menu I blurred the Chrome window and then focused on it again.
![menu bug](https://cloud.githubusercontent.com/assets/932103/26766431/d0222c72-495f-11e7-802d-8393548d306e.gif)

#### Expected behavior
- The menu could stay open but then it needs to close on a click outside the menu
- Or the menu closes on blurring the window

**Comment by pkerpedjiev** [comment]
Doesn't seem to be an issue any more.
