### ISSUE TITLE
Dragging a link onto page shows forever blue drop indicator

### ISSUE THREAD

**Issue by flekschas** [hms-dbmi/higlass#122]
_Commit_: latest

#### Steps to reproduce
1. click and drag and link from within the website onto it and release the mouse

![argh](https://user-images.githubusercontent.com/932103/28347258-fe1015d8-6c03-11e7-8cdb-f34e352648b5.gif)

#### Observed behavior
- Forever "drop config here"

#### Expected behavior
- Indicator should disappear after releasing the mouse
- Indicator should close on ESC
- There should be an X button to explicitly close it

**Comment by pkerpedjiev** [comment]
Fixed a while ago.
