### ISSUE TITLE
afmhot is an ambiguous color map

### ISSUE THREAD

**Issue by flekschas** [hms-dbmi/higlass#123]
_Commit_: latest

#### Steps to reproduce
1. Select afmhot

#### Observed behavior
- The highest and no value are both white since the background of empty bins is transparent.

![screen shot 2017-08-07 at 3 52 48 pm](https://user-images.githubusercontent.com/932103/29043286-82a76a9c-7b88-11e7-8629-090b28cc8131.png)

#### Expected behavior
- The background should not be transparent or the bins with no value should be filled with the color for 0.

**Comment by pkerpedjiev** [comment]
This is fixed in later bins since the background can be adjusted and NaN values are displayed as transparent.
