### ISSUE TITLE
Problem with .15 version in Top tracks

### ISSUE THREAD

**Issue by nadabrovitxka** [hms-dbmi/higlass#130]
Hi,
With this new update whenever I try loading HiC in top panels it freezes. The same dataset can be introduced in the central panel. This is both locally and on the website.

**Comment by pkerpedjiev** [comment]
Oh my!! Should be fixed in both the website (<shift> - reload) and v0.2.16 of the docker container.

Thank you for pointing this out! I need to be more diligent about running unit tests before making major features public :-/
