### ISSUE TITLE
When hiding color bar the color bar slider remains visible

### ISSUE THREAD

**Issue by flekschas** [hms-dbmi/higlass#131]
_Commit_: higlass.io

#### Steps to reproduce
1. Show colorbar
2. Hide colorbar

#### Observed behavior
![screen shot 2017-08-30 at 4 18 58 pm](https://user-images.githubusercontent.com/932103/29893135-16fbd11a-8d9f-11e7-9828-6d5a2bf8c543.png)

#### Expected behavior
- Colorbar should hide too

**Comment by pkerpedjiev** [comment]
Fixed in 0.8.35.
