### ISSUE TITLE
Flipping the horizontal heatmap only works once

### ISSUE THREAD

**Issue by flekschas** [hms-dbmi/higlass#132]
_Commit_: higlass.io

#### Steps to reproduce
1. Select Flip Matrix > Yes
2. Select Flip Matrix > Yes
3. Select Flip Matrix > No

#### Observed behavior
- Matrix flips ones but can't be flipped back

#### Expected behavior
- Matrix flipping should be undoable

**Comment by pkerpedjiev** [comment]
Seems to only be an issue in `vertical-heatmap-track`

**Comment by pkerpedjiev** [comment]
Rerender wasn't calling `zoomed`, which is what sets the scale of pMain, causing it to draw a flipped heatmap.
