### ISSUE TITLE
Colorbar and context menu clash

### ISSUE THREAD

**Issue by flekschas** [hms-dbmi/higlass#133]
_Commit_: higlass.io

#### Steps to reproduce
1. Hover over the colorbar

#### Observed behavior
- Once the user moves the mouse curser a tiny little bit too far up (above the end of the colorbar slider) the context menu pops up and permits interactive with the colorbar slider.

![screen shot 2017-08-30 at 4 22 47 pm](https://user-images.githubusercontent.com/932103/29893272-7ef189b8-8d9f-11e7-9a61-5d8d9d7dac37.png)

#### Expected behavior
- The position of the context menu should be automatically adjusted when the colorbar is visible or the context menu should be he hidden behind a right mouse click (original right mouse clicks could still be triggered with ALT+right click)

**Comment by pkerpedjiev** [comment]
Fixed by Fritz.
