### ISSUE TITLE
SVG export doesn't work when there are two viewports side by side

### ISSUE THREAD

**Issue by danielsday** [hms-dbmi/higlass#153]
When I create a viewport, add gene annotation and chromosome tracks to the top and left size, copy the viewport, then replace the track in the second viewport with a different data set, and then try to run SVG export, I get no output in either Firefox or Chrome.

When I reload the app and just load one track, I can use SVG export just fine.

**Comment by pkerpedjiev** [comment]
This can be tricky to reproduce. Using this link: http://higlass.io/app/?config=OPPFtzbuR76vtUIshTEOGA seems to lead to failed exports. I'll look into this ASAP.

**Comment by pkerpedjiev** [comment]
Should be fixed in higlass v0.8.44. Docker v0.2.25.
