### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by nvictus** [hms-dbmi/higlass#156]
_Commit_: 

#### Steps to reproduce
1. Open a tab in chrome

#### Observed behavior
- A blank placeholder favicon appears. Sometimes annoying favicons from using public wifi services get cached and reused.

#### Expected behavior
- A HiGlass favicon.

**Comment by flekschas** [comment]
We could use the favicon from higlass-app until they got a new logo designed. (See favicon on the right tab vs the left in Chrome)

![screen shot 2017-11-17 at 8 42 13 am](https://user-images.githubusercontent.com/932103/32950140-4989f5be-cb73-11e7-86ab-a47b5c1d6f29.png)

**Comment by nvictus** [comment]
this seems to be resolved.
