### ISSUE TITLE
Non "standard" 1D tracks do not appear to be exported correctly in SVG export

### ISSUE THREAD

**Issue by danielsday** [hms-dbmi/higlass#157]
Using version 0.2.18, when I add a track I created from a BED file, I cannot seem to be able to export the BED annotation that I created and uploaded myself into the SVG output.

I am also using a split screen (two views) if that makes a difference.

**Comment by pkerpedjiev** [comment]
Any chance you could attach a sample track to this issue so I can try it out myself?

**Comment by danielsday** [comment]
Here you go

[sampletrack.zip](https://github.com/hms-dbmi/higlass/files/1331785/sampletrack.zip)

**Comment by pkerpedjiev** [comment]
Should be fixed in docker version `v0.2.24`.

Your annotations don't have text do they?
