### ISSUE TITLE
Exporting the view as link when using a non-standard port

### ISSUE THREAD

**Issue by hakanozadam** [hms-dbmi/higlass#162]
_Commit_: 

#### Steps to reproduce
1. Start the server on a different port. For example 8001, i.e.,  http://146.189.165.200:8001 is the address the server is located at.
2. Generate a link for a view.
http://146.189.165.200/app/?config=LBH1piIDRMeVdMmF84KBZg

#### Observed behavior
- The pot number is not added to the link. So, the generated link will direct to the standard http port. Hence the page won't be displayed.

#### Expected behavior
- Seeing the port number in the generated link
For example:
http://146.189.165.200:8001/app/?config=LBH1piIDRMeVdMmF84KBZg

**Comment by pkerpedjiev** [comment]
Fixed in v0.2.32.
