### ISSUE TITLE
Context menus can cross the lower boundary of the page and become inaccessible

### ISSUE THREAD

**Issue by nvictus** [hms-dbmi/higlass#169]
_Commit_: 

#### Steps to reproduce
1. Add a bottom track to the bottom of a full screen app
2. Navigate through the tool bar

#### Observed behavior
- Some menu items are inaccessible because the rest of the menu is cut off from the page

![image](https://user-images.githubusercontent.com/1270651/32374713-3da325f8-c075-11e7-82f2-686db572c8c6.png)

#### Expected behavior
- Context menu placement should adjust accordingly, as it seems to do with the left/right page boundaries.

**Comment by pkerpedjiev** [comment]
Should be fixed in the latest Docker. 

![image](https://user-images.githubusercontent.com/2143629/32379022-fc3861b2-c071-11e7-9dab-289fd19366e3.png)

**Comment by pkerpedjiev** [comment]
Will close when the latest Docker is pushed to the public site.

**Comment by nvictus** [comment]
I believe this is fixed now. Closing.
