### ISSUE TITLE
Zoom linking depends on view size

### ISSUE THREAD

**Issue by Phlya** [hms-dbmi/higlass#172]
Go to here (modified Schwarzer 2017 example): http://higlass.io/app/?config=F072ptbIRHO1qFcD8WvngA
Lock zoom and (and position) between the views - the left one will remain at 16K resolution, but the right one - at 8K. 
If you make the left view smaller, the resolution will go to 8K.

I would expect both views to sync and show the lower resolution of the two after they are linked.

**Comment by flekschas** [comment]
This behavior was expected. You might want to have I multiple linked views with different resolutions. But I think we can close this as there's an option which does exactly what is requested called `Take and lock zoom and location with`.

@Phlya If this option does not help you please reopen the issue.
