### ISSUE TITLE
SVG import in Illustrator failed

### ISSUE THREAD

**Issue by jerceg** [hms-dbmi/higlass#173]
_Commit_: 

#### Steps to reproduce
1.Opening HiGlass SVG output in Adobe Illustrator (CS4 or CS6) failed.

#### Observed behavior
- Error: 'This SVG is Invalid. Validate it before opening.'

#### Expected behavior
-

**Comment by pkerpedjiev** [comment]
Should be fixed. See https://github.com/hms-dbmi/higlass/issues/176.

**Comment by jerceg** [comment]
Sounds great. Thank you!


On May 31, 2018, at 10:00 AM, Peter Kerpedjiev <notifications@github.com<mailto:notifications@github.com>> wrote:


Should be fixed. See #176<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_hms-2Ddbmi_higlass_issues_176&d=DwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=OmW0Xf3lCrVEdphBa5-y2OWG21vNW4vvptB4oXA-GZM&m=KlRXWWTN64wlr5jGeC7FpZsYpLbCAbBEcZuk_JVlvtc&s=cRpTc8cEukQ54tE7nUYQTGydIWwljnfHeJMRoJkmQ8c&e=>.
