### ISSUE TITLE
Simple bed files

### ISSUE THREAD

**Issue by Phlya** [hms-dbmi/higlass#174]
Hi, is there a simple way to visualize basic bed files in higlass? I guess it's possible to go through the whole gene annotation process, but this seems very convoluted for just showing a few lines.

**Comment by pkerpedjiev** [comment]
Yes! You just have aggregate them using clodius:

```
      clodius aggregate bedfile \
          --assembly hg19 \
          somefile.bed
```

And then ingest them using `--filetype beddb` and `--datatype bed-like`:

```
sudo docker exec higlass-container python higlass-server/manage.py \
  ingest_tileset \
  --filename /tmp/somefile.beddb \
  --datatype bed-like \
  --filetype beddb
``` 

There is documentation in the new [draft documentation here](https://hms-dbmi.github.io/higlass-docs/track_types.html#bed-like) and [here](https://hms-dbmi.github.io/higlass-docs/data_preparation.html#bed-files).

**Comment by Phlya** [comment]
Ah, cool, thank you!

**Comment by Phlya** [comment]
OK mmm I am not sure whether I should just continue this here, but somehow after ingesting the file doesn't appear in the list of available datasets... I even restarted the whole docker container. And it is listed in the admin interface.

**Comment by pkerpedjiev** [comment]
Sorry, can you try with `--datatype bedlike`? (no dash in bedlike)

**Comment by Phlya** [comment]
Yep, that's it, thanks!
