### ISSUE TITLE
no menu on higlass

### ISSUE THREAD

**Issue by Yananiko** [hms-dbmi/higlass#179]
I tried to set up higlass on my computer yesterday but I had some problems because I have Windows Home eidition. So instead of Docker, I am now using Docker Toolbox. Things seemed to be working but when I open higlass in the browser, it has no menu - I just see "higlass" in the upper left corner of the window and the short description of what it is but I cannot open any documents. I would appreciate any help with solving this problem. I was told to use Chrome but it did not help - looks the same irrespective of the browser I am using.

**Comment by nvictus** [comment]
Could you describe or post a snapshot of what you see in the javascript console on Chrome (the panel that pops up when you type ctrl+shift+J) when you navigate to HiGlass?

**Comment by Yananiko** [comment]
![untitled](https://user-images.githubusercontent.com/33728508/32908978-f764c530-cb0d-11e7-9a3c-8471bf6ee312.png)

**Comment by nvictus** [comment]
It looks the server running on a local private network. Is that your IP address in the address bar or that of another machine (i.e. is the server running on your computer)?

**Comment by Yananiko** [comment]
This is not my IP address.

**Comment by pkerpedjiev** [comment]
Hi @Yananiko! You probably have to specify a `SITE_URL` parameter to the docker container to run on it on an IP other than localhost:

```
docker run --detach \
           --publish 8989:80 \
           --volume ~/hg-data:/data \
           --volume ~/tmp:/tmp \
           --name higlass-container \
           -e SITE_URL=192.168.99.100 \
           gehlenborglab/higlass:v0.2.45
```

This lets the docker container know that it should accept requests coming from that server. Otherwise it rejects them, leading to the BAD REQUEST error that you're seeing.

There's an example on the wiki here: https://github.com/hms-dbmi/higlass/wiki

**Comment by Yananiko** [comment]
Yes, thank you. We tried this and it worked so the problem was solved.
