### ISSUE TITLE
Odd blue bar in the 1D track

### ISSUE THREAD

**Issue by flekschas** [hms-dbmi/higlass#18]
_Commit_: cafdba59fd0842cc279b8ad3708c8a955bfc872a

#### Steps to reproduce
1. Zoom in enough

#### Observed behavior
- All of a sudden a blue bar appears

![jan -31-2017 16-17-05](https://cloud.githubusercontent.com/assets/932103/22484837/233cf7d4-e7d1-11e6-8772-1a26b95eda94.gif)

#### Expected behavior
- The blue bar should not appear all of a sudden

**Comment by pkerpedjiev** [comment]
Fixed:

![image](https://cloud.githubusercontent.com/assets/2143629/22629256/917dd776-ebb0-11e6-8438-37d1f152d468.png)

The current exon unions code was concatenating exons that were on different chromosomes.
