### ISSUE TITLE
Gene disappears when the tile it contains it is removed

### ISSUE THREAD

**Issue by pkerpedjiev** [hms-dbmi/higlass#181]
In mm10:

![dec-12-2017 13-49-47](https://user-images.githubusercontent.com/2143629/33902552-587371ac-df43-11e7-861f-e7122491ee36.gif)

**Comment by mimakaev** [comment]
I have the same problem. Especially tricky when you zoom into very large genes. 

Try zooming in from here: http://higlass.io/app/?config=YJfY-iNFQai89RhG1JCcWQ

**Comment by pkerpedjiev** [comment]
Looks like this was just a poorly tiled gene annotation set. I replaced it. Should be fixed with a hard refresh of the browser.
