### ISSUE TITLE
Question: Pre-populate page?

### ISSUE THREAD

**Issue by aakashsur** [hms-dbmi/higlass#184]
How do you pre-populate the page with a certain visualization like you do with your examples? I see there is a config option, i.e. (http://higlass.io/app/?config=OPPFtzbuR76vtUIshTEOGA). How are these setup?

**Comment by pkerpedjiev** [comment]
Very easily. Just create the view you want to share and the click on "Export views as link": 

![image](https://user-images.githubusercontent.com/2143629/34176428-d4d306b0-e4cd-11e7-82ad-cb30db36a8b4.png)

**Comment by aakashsur** [comment]
Ahhh, awesome, so easy....
