### ISSUE TITLE
Auto Zoom to Data Extent

### ISSUE THREAD

**Issue by aakashsur** [hms-dbmi/higlass#185]
Hi, great app, love using it. We are working with a much smaller genome (32mb) and when I load a matrix, it initially appears blank until I select "zoom to data extent". I'm guessing this is because of the difference in genome size, but am I following the workflow correctly, or would auto zoom to data extent by an enhancement?

**Comment by pkerpedjiev** [comment]
Thanks! You're exactly right in your diagnosis. The default view is set up for the human genome.

Auto zooming to data extent would actually be very nice to have and easy to implement. Just have to be careful to not apply it if not necessary. For example, if somebody is looking at a particular gene and wants to add a new track. We wouldn't to zoom out away from the gene. So it should only happen if the newly added dataset is much smaller than the current view.

**Comment by aakashsur** [comment]
Gotcha, keep up the great work!

**Comment by flekschas** [comment]
Implemented: https://github.com/hms-dbmi/higlass/blob/master/app/scripts/api.js#L60
