### ISSUE TITLE
Display heatmap values on mouseover

### ISSUE THREAD

**Issue by pkerpedjiev** [hms-dbmi/higlass#191]
There should be a way to display the raw values in the heatmap on mouseover events.

**Comment by flekschas** [comment]
Possible using the mouseMoveZoom API. Does that close the ticket? @pkerpedjiev

**Comment by pkerpedjiev** [comment]
I'm going to leave it open for now because I'd like to add a small popup that shows the data value on mouseover.

**Comment by pkerpedjiev** [comment]
Implemented in v1.0.0-alpha.3
