### ISSUE TITLE
Pre-load tracks on app start

### ISSUE THREAD

**Issue by danledinh** [hms-dbmi/higlass#194]
How do I modify the viewconf script to open the app with pre-loaded tracks (e.g. gene annotations on the top and left axes) ?

Currently the default script looks like this:
```
{
  "editable": true,
  "zoomFixed": false,
  "trackSourceServers": [
  "/api/v1"
  ],
  "exportViewUrl": "/api/v1/viewconfs/",
  "views": [
    {
      "tracks": {
        "top": [],
        "left": [],
        "center": [],
        "right": [],
        "bottom": []
      },
      "initialXDomain": [ 0, 3200000000 ],
      "initialYDomain": [ 0, 3200000000 ],
      "layout": {
        "w": 12,
        "h": 12,
        "x": 0,
        "y": 0,
        "moved": false,
        "static": false
      }
    }
  ],
  "zoomLocks": {
    "locksByViewUid": {},
    "locksDict": {}
  },
  "locationLocks": {
    "locksByViewUid": {},
    "locksDict": {}
  }
}
```

**Comment by pkerpedjiev** [comment]
Have you tried changing the `default` viewconf in the admin interface?

See this issue:

https://github.com/hms-dbmi/higlass-docker/issues/144

**Comment by danledinh** [comment]
Perhaps, there is a misunderstanding. I would like to have the hg38 track already showing on the axis when navigating to the app website (akin to how the higlass demo website has data and tracks already running).

**Comment by pkerpedjiev** [comment]
This should do precisely that.  When you load `http://localhost:8888/app`, this looks for a local viewconf with the ID `default`. If you change the contents of this viewconf using the admin API, you should see your desired default tracks.

**Comment by danledinh** [comment]
Thanks. I got it to work! I just didn't know where to place the settings script. Here is how I added my track to the top axis:
```
"tracks": {
        "top": [
          {
            "type": "horizontal-gene-annotations",
            "width": 60,
            "tilesetUid": "OM4_zObIRa2_8rIEpUNVvQ",
            "server": "/api/v1",
            "position": "top",
            "name": "Gene Annotations"
          }
        ],
...
```
