### ISSUE TITLE
Colorscale features

### ISSUE THREAD

**Issue by pkerpedjiev** [hms-dbmi/higlass#2]
Desired functionality:

Leonid:
- automatic linear scale;
- automatic log scale;
- a manually adjustable colorscale, where a user can specify a range (min,max) of values that are mapped onto a colormap; pixels with values above the max are shown by the top color in the colormap, while pixels below min are shown with the lowest color in the colormap. i.e. a use determines the trimming values.
- and, most importantly, an option of having a colorscale change automatically upon zooming!

an automatic scale can take 95% range of values, trimming top 2.5% and 2.5% bottom (or 90% and trip 5% on each side).

Job:

Have an option to specify the colors in the colorscale. Specifically ""white,orange,red,darkRed".

Bryan:

From the cworld-dekker perl gd library (dekker.pm)

default color pos/neg color maps:
$availableColorScales{ dekkerPositive } = "white,orange,red,darkRed"; 
$availableColorScales{ dekkerNegative } = "white,cyan,blue,darkBlue";

Then the above colors are defined as RGBa tuples:
(null is for missing NaN/None values)

```
@{$availableColors{ null }} = (150,150,150,0);

@{$availableColors{ white }} = (255,255,255,$transparency); 
@{$availableColors{ black }} = (0,0,0,$transparency);

@{$availableColors{ red }} = (255,0,0,$transparency);
@{$availableColors{ orange }} = (255,165,0,$transparency);
@{$availableColors{ darkRed }} = (90,0,0,$transparency);

@{$availableColors{ blue }} = (0,0,255,$transparency);
@{$availableColors{ cyan }} = (0,255,255,$transparency);
@{$availableColors{ darkBlue }} = (0,0,90,$transparency);
```

The default is to set the color range to be 2.5% - 97.5% of the score dist.
(we exclude the x=y and abs(x-y)==1 diagonals in this dist.)

Then color is set as a simple linear scale between the defined colors in the colorMap.
128 total colors are used by default.
Default is no transparency.

**Comment by pkerpedjiev** [comment]
Color scales are fully adjustable now.

**Comment by yezhengSTAT** [comment]
Hello,
Autoscaling the color range by trimming the top 2.5% may cause the TAD structures super hard to distinguish. I saw there have been other comments about giving the users an option to set the max color limit as Juicebox does and I want to know if such function will be updated soon?
Thanks for creating such fancy Hi-C visualization tool! Really want to utilize it for the figures in our manuscript.

Thanks,
Ye

**Comment by pkerpedjiev** [comment]
Yes, this is really high priority! See the similar issue here: https://github.com/hms-dbmi/higlass/issues/171
