### ISSUE TITLE
Unable to select track context buttons of the bottom track when its height is to low

### ISSUE THREAD

**Issue by flekschas** [hms-dbmi/higlass#200]
_Commit_: Higlass.op

#### Steps to reproduce
1. Make a bottom track's height very small

#### Observed behavior
![jan-18-2018 22-24-04](https://user-images.githubusercontent.com/932103/35171277-3b08ea00-fd31-11e7-9e7a-8ba59371c993.gif)

#### Expected behavior
Should be clickable

**Comment by pkerpedjiev** [comment]
I think this is fixed. Feel free to reopen if it isn't.
