### ISSUE TITLE
Add an easy way to display the whole matrix

### ISSUE THREAD

**Issue by flekschas** [hms-dbmi/higlass#21]
Right now the user has to manually figure out what the start and end loci are. It would be great if simple omission of the start and end loci is interpreted as: display the matrix from the beginning to the end

**Comment by pkerpedjiev** [comment]
Related to: https://github.com/hms-dbmi/higlass/issues/185

**Comment by pkerpedjiev** [comment]
Use `Zoom to data extent`:

![image](https://user-images.githubusercontent.com/2143629/40786977-6fce9406-64ba-11e8-94fa-2e84888ede9c.png)
