### ISSUE TITLE
Trouble adding tracks

### ISSUE THREAD

**Issue by richgill8** [hms-dbmi/higlass#211]
Hello,

I am having issues loading any data into higlass. I started up higlass using Docker as instructed, and while the menu loads, upon pressing the + button to add tracks, the buttons for top/center/left/etc are unresponsive. I tried 8989 as well and the problem persists.

Please advise.

Thanks!

_Commit_: 

#### Steps to reproduce
1. docker run --detach --publish 8888:80 --volume ~/hg-data:/data --volume ~/hg-tmp:/tmp --name higlass-container gehlenborglab/higlass:v0.2.45

2. localhost:8888

#### Observed behavior
- 
<img width="888" alt="screen shot 2018-02-06 at 1 59 07 pm" src="https://user-images.githubusercontent.com/14060896/35878657-ec2c3940-0b46-11e8-9a1a-e4d5bace7799.png">

#### Expected behavior
- Menu of datasets

**Comment by pkerpedjiev** [comment]
Hey, really sorry about that. Just upgrade to the latest docker version (v0.2.57) and it should be fixed.

**Comment by richgill8** [comment]
Hi Peter, unfortunately that did not resolve the issue.

**Comment by pkerpedjiev** [comment]
Could you hold down the shift key and click "reload" on your browser using the newest docker container? 

I just ran the following on my computer, opened localhost:8989 and hit shift-reload and could add new tracks.

```
docker stop higlass-container; 
docker rm higlass-container;

docker pull gehlenborglab/higlass:v0.2.57 # Ensure that you have the latest.

docker run --detach \
           --publish 8989:80 \
           --volume ~/hg-data \
           --volume ~/hg-tmp:/tmp \
           --name higlass-container \
           gehlenborglab/higlass:v0.2.57
```

**Comment by richgill8** [comment]
That worked - thanks very much!
