### ISSUE TITLE
Pairwise Chromosome Labels Behavior

### ISSUE THREAD

**Issue by aakashsur** [hms-dbmi/higlass#214]
_Commit_: Latest

#### Steps to reproduce
1. When trying to add the chromosome grid and chromosome labels. By going to add track -> center ->  selecting "Pairwise Chromosome Labels" (where the default selection is 2d-chromosome-grid 

![image](https://user-images.githubusercontent.com/7614271/35903038-51333a1e-0b92-11e8-9b82-d1737c2fe8d2.png)

#### Observed behavior
- Nothing happens. Perhaps I misunderstood the function of that the "Pairwise Chromosome Labels" are supposed to do. Nevertheless, even though nothing shows up, it adds a track to the existing central track:

![image](https://user-images.githubusercontent.com/7614271/35903168-e1a7a44a-0b92-11e8-8c46-8e13d4c1d54e.png)

I did notice this in the console:

![image](https://user-images.githubusercontent.com/7614271/35903095-92355d4e-0b92-11e8-8cb8-403392bd4bcf.png)

The same thing happens if I select 2d-chromosome-label:

![image](https://user-images.githubusercontent.com/7614271/35903198-f9f44508-0b92-11e8-951a-ebf71f032ffc.png)

With the same error:

![image](https://user-images.githubusercontent.com/7614271/35903209-0320dc22-0b93-11e8-9606-aa3c00c7f998.png)

#### Expected behavior
- To be fair, I'm not sure what the 2d-chromosome-labels are supposed to look like, but the grid does work if I select the actual grid from the right file:

![image](https://user-images.githubusercontent.com/7614271/35903308-6dfa3660-0b93-11e8-82db-2162dddaa6c2.png)

And I get: 

![image](https://user-images.githubusercontent.com/7614271/35903316-785e26a2-0b93-11e8-9ad2-4454177861e6.png)

Although when I select 2d-chromosome-labels from that file/track, it throws an error as well.

**Comment by pkerpedjiev** [comment]
That's a bug. You should definitely see something :) I'll try to get it fixed ASAP.

**Comment by pkerpedjiev** [comment]
Should be fixed in the latest docker container (v0.2.60).
