### ISSUE TITLE
Required resources

### ISSUE THREAD

**Issue by Phlya** [hms-dbmi/higlass#215]
Hi, I am considering setting up a virtual machine to host higlass. The virtual machine creation service is provided by our university, and to create one I obviously need to specify the resources required, i.e. ram and cpu. So I am wondering what kind of resources are required to run higlass smoothly? Thanks!

**Comment by pkerpedjiev** [comment]
You should be fine with a two core CPU and 4Gb of RAM. You could probably even do with less RAM but we haven't tried. Also, make sure that the disk you create has sufficient space for all the data that you plan to upload.

**Comment by Phlya** [comment]
Thank you, this is very helpful!

**Comment by pkerpedjiev** [comment]
Also, take a look at this script: https://github.com/hms-dbmi/higlass-docker/blob/master/start_production.sh

It will set up a caching container that will offer a nice speed boost.

**Comment by Phlya** [comment]
Cool, thank you!
