### ISSUE TITLE
Color map is not properly synchronized

### ISSUE THREAD

**Issue by flekschas** [hms-dbmi/higlass#216]
_Commit_: 

#### Steps to reproduce
1. start here: http://higlass.io/app/?config=BrgmDWRVQF23nFCZG9rtKA
2. pan a bit around until the next tile is loaded

#### Observed behavior
<img width="1024" alt="screen shot 2018-02-07 at 10 31 19 pm" src="https://user-images.githubusercontent.com/932103/35954302-f5182120-0c56-11e8-97e6-02944a8ee9ad.png">

![feb-07-2018 22-31-53](https://user-images.githubusercontent.com/932103/35954326-10729ca2-0c57-11e8-9b9c-62863284b207.gif)

#### Expected behavior
-

**Comment by pkerpedjiev** [comment]
Fixed in the develop branch. Should be in the next major release (v1.0).
