### ISSUE TITLE
bigwig conversion

### ISSUE THREAD

**Issue by zhanyinx** [hms-dbmi/higlass#220]
Hi,

I am trying to convert bigwig file to hitile and it failed.

The command line I used:
clodius aggregate bigwig $INPUT --output-file $INPUT.hitile

The error message I got is the following:

there
chrom_order: ['chr1', 'chr2', 'chr3', 'chr4', 'chr5', 'chr6', 'chr7', 'chr8', 'chr9', 'chr10', 'chr11', 'chr12', 'chr13', 'chr14', 'chr15', 'chr16', 'chr17', 'chr18', 'chr19', 'chr20', 'chr21', 'chr22', 'chrX', 'chrY', 'chrM', 'chr6_ssto_hap7', 'chr6_mcf_hap5', 'chr6_cox_hap2', 'chr6_mann_hap4', 'chr6_apd_hap1', 'chr6_qbl_hap6', 'chr6_dbb_hap3', 'chr17_ctg5_hap1', 'chr4_ctg9_hap1', 'chr1_gl000192_random', 'chrUn_gl000225', 'chr4_gl000194_random', 'chr4_gl000193_random', 'chr9_gl000200_random', 'chrUn_gl000222', 'chrUn_gl000212', 'chr7_gl000195_random', 'chrUn_gl000223', 'chrUn_gl000224', 'chrUn_gl000219', 'chr17_gl000205_random', 'chrUn_gl000215', 'chrUn_gl000216', 'chrUn_gl000217', 'chr9_gl000199_random', 'chrUn_gl000211', 'chrUn_gl000213', 'chrUn_gl000220', 'chrUn_gl000218', 'chr19_gl000209_random', 'chrUn_gl000221', 'chrUn_gl000214', 'chrUn_gl000228', 'chrUn_gl000227', 'chr1_gl000191_random', 'chr19_gl000208_random', 'chr9_gl000198_random', 'chr17_gl000204_random', 'chrUn_gl000233', 'chrUn_gl000237', 'chrUn_gl000230', 'chrUn_gl000242', 'chrUn_gl000243', 'chrUn_gl000241', 'chrUn_gl000236', 'chrUn_gl000240', 'chr17_gl000206_random', 'chrUn_gl000232', 'chrUn_gl000234', 'chr11_gl000202_random', 'chrUn_gl000238', 'chrUn_gl000244', 'chrUn_gl000248', 'chr8_gl000196_random', 'chrUn_gl000249', 'chrUn_gl000246', 'chr17_gl000203_random', 'chr8_gl000197_random', 'chrUn_gl000245', 'chrUn_gl000247', 'chr9_gl000201_random', 'chrUn_gl000235', 'chrUn_gl000239', 'chr21_gl000210_random', 'chrUn_gl000231', 'chrUn_gl000229', 'chrUn_gl000226', 'chr18_gl000207_random']
assembly size (max-length) 3137161264
max-width 4294967296.0
max_zoom: 22.0
chunk-size: 16777216
chrom-order ['chr1' 'chr2' 'chr3' 'chr4' 'chr5' 'chr6' 'chr7' 'chr8' 'chr9' 'chr10'
 'chr11' 'chr12' 'chr13' 'chr14' 'chr15' 'chr16' 'chr17' 'chr18' 'chr19'
 'chr20' 'chr21' 'chr22' 'chrX' 'chrY' 'chrM' 'chr6_ssto_hap7'
 'chr6_mcf_hap5' 'chr6_cox_hap2' 'chr6_mann_hap4' 'chr6_apd_hap1'
 'chr6_qbl_hap6' 'chr6_dbb_hap3' 'chr17_ctg5_hap1' 'chr4_ctg9_hap1'
 'chr1_gl000192_random' 'chrUn_gl000225' 'chr4_gl000194_random'
 'chr4_gl000193_random' 'chr9_gl000200_random' 'chrUn_gl000222'
 'chrUn_gl000212' 'chr7_gl000195_random' 'chrUn_gl000223' 'chrUn_gl000224'
 'chrUn_gl000219' 'chr17_gl000205_random' 'chrUn_gl000215' 'chrUn_gl000216'
 'chrUn_gl000217' 'chr9_gl000199_random' 'chrUn_gl000211' 'chrUn_gl000213'
 'chrUn_gl000220' 'chrUn_gl000218' 'chr19_gl000209_random' 'chrUn_gl000221'
 'chrUn_gl000214' 'chrUn_gl000228' 'chrUn_gl000227' 'chr1_gl000191_random'
 'chr19_gl000208_random' 'chr9_gl000198_random' 'chr17_gl000204_random'
 'chrUn_gl000233' 'chrUn_gl000237' 'chrUn_gl000230' 'chrUn_gl000242'
 'chrUn_gl000243' 'chrUn_gl000241' 'chrUn_gl000236' 'chrUn_gl000240'
 'chr17_gl000206_random' 'chrUn_gl000232' 'chrUn_gl000234'
 'chr11_gl000202_random' 'chrUn_gl000238' 'chrUn_gl000244' 'chrUn_gl000248'
 'chr8_gl000196_random' 'chrUn_gl000249' 'chrUn_gl000246'
 'chr17_gl000203_random' 'chr8_gl000197_random' 'chrUn_gl000245'
 'chrUn_gl000247' 'chr9_gl000201_random' 'chrUn_gl000235' 'chrUn_gl000239'
 'chr21_gl000210_random' 'chrUn_gl000231' 'chrUn_gl000229' 'chrUn_gl000226'
 'chr18_gl000207_random']
chrom: chr1
position: 1 progress: 0.00 elapsed: 3.78 remaining: 11858479207.83
len(data_buffers[curr_zoom]) 16777216
positions[curr_zoom]: 0
position: 16777217 progress: 0.01 elapsed: 11.54 remaining: 2145.87
len(data_buffers[curr_zoom]) 16777216
positions[curr_zoom]: 16777216
position: 33554433 progress: 0.01 elapsed: 19.08 remaining: 1764.84
len(data_buffers[curr_zoom]) 16777216
positions[curr_zoom]: 33554432
position: 50331649 progress: 0.02 elapsed: 26.61 remaining: 1631.98
len(data_buffers[curr_zoom]) 16777216
positions[curr_zoom]: 50331648
position: 67108865 progress: 0.02 elapsed: 34.23 remaining: 1565.87
len(data_buffers[curr_zoom]) 16777216
positions[curr_zoom]: 67108864
position: 83886081 progress: 0.03 elapsed: 42.24 remaining: 1537.47
len(data_buffers[curr_zoom]) 16777216
positions[curr_zoom]: 83886080
position: 100663297 progress: 0.03 elapsed: 50.00 remaining: 1508.39
len(data_buffers[curr_zoom]) 16777216
positions[curr_zoom]: 100663296
position: 117440513 progress: 0.04 elapsed: 57.86 remaining: 1487.63
len(data_buffers[curr_zoom]) 16777216
positions[curr_zoom]: 117440512
position: 134217729 progress: 0.04 elapsed: 65.40 remaining: 1463.29
len(data_buffers[curr_zoom]) 16777216
positions[curr_zoom]: 134217728
position: 150994945 progress: 0.05 elapsed: 72.99 remaining: 1443.49
len(data_buffers[curr_zoom]) 16777216
positions[curr_zoom]: 150994944
position: 167772161 progress: 0.05 elapsed: 80.83 remaining: 1430.54
len(data_buffers[curr_zoom]) 16777216
positions[curr_zoom]: 167772160
Traceback (most recent call last):
  File "/home_fmi/01/zhanyinx/bin/clodius", line 11, in <module>
    sys.exit(cli())
  File "/work2/ggiorget/zhan/bin/Python-2.7.12/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/work2/ggiorget/zhan/bin/Python-2.7.12/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/work2/ggiorget/zhan/bin/Python-2.7.12/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/work2/ggiorget/zhan/bin/Python-2.7.12/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/work2/ggiorget/zhan/bin/Python-2.7.12/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/work2/ggiorget/zhan/bin/Python-2.7.12/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/work2/ggiorget/zhan/bin/Python-2.7.12/lib/python2.7/site-packages/clodius/cli/aggregate.py", line 1100, in bigwig
    _bigwig(filepath, chunk_size, zoom_step, tile_size, output_file, assembly, chromsizes_filename, chromosome)
  File "/work2/ggiorget/zhan/bin/Python-2.7.12/lib/python2.7/site-packages/clodius/cli/aggregate.py", line 666, in _bigwig
    values = bwf.values(chrom, counter, counter + remaining)
RuntimeError: Invalid interval bounds!

Could you please help me to solve this problem?

Thanks in advance
Zhan

**Comment by pkerpedjiev** [comment]
Would you mind posting the bigWig file that caused the error?

**Comment by zhanyinx** [comment]
I downloaded from ENCODE

This is the file
https://www.encodeproject.org/files/ENCFF001ZPH/@@download/ENCFF001ZPH.bigWig

**Comment by zhanyinx** [comment]
I solved the problem by adding the option --assembly mm9.

I would update the bigwig conversion in the docs page: https://github.com/hms-dbmi/higlass/wiki

**Comment by pkerpedjiev** [comment]
OK, great to hear! I added a note to the wiki mentioning the `--assembly` option. You can also pass in a `--chromsizes-filename` for non-standard assemblies.

Thanks for reporting this.
