### ISSUE TITLE
Download cool files

### ISSUE THREAD

**Issue by eaststar0** [hms-dbmi/higlass#221]
_Commit_: 
Hi,
Is there a way I can download the cool files that are uploaded already?
Thank you very much for all the great works help.

Best regards,

Lee

**Comment by pkerpedjiev** [comment]
No, unfortunately that's not possible at the moment.

We could look into making that available for local installations but the size of the files available on our public site would make this an expensive option to have.

**Comment by gtrichard** [comment]
I'm also interested to get the `.cool` files available for example on the docker image of HiGlass, is it possible to download some of these matrices?

Best,
Gautier

**Comment by pkerpedjiev** [comment]
I recommend checking out https://data.4dnucleome.org/ or asking on our Slack channel (http://bit.ly/higlass-slack) and somebody can probably provide you a bootleg cool file ;-)
