### ISSUE TITLE
Track selection window not showing anymore (hidden)?

### ISSUE THREAD

**Issue by rdacemel** [hms-dbmi/higlass#224]
_Commit_: latest docker image 

#### Steps to reproduce
1. Launch higlass docker image from server (Debian 8 Jessie) and open higlass page either in Mozilla (52.0.1) or Chrome (57.0.2987.110)

#### Observed behavior
- Not able to add tracks because the window that used to appear after choosing center, top, etc to select the tracks does not show anymore.  It seems to be hidden behind the normal canvas when using developing mode in the browser. Barely know nothing about web stuff to be more specific...

#### Expected behavior
- Being able to see the window with the tracks and open them. 

It was working nicely in every computer in the lab but suddenly this stopped working.

**Comment by pkerpedjiev** [comment]
My apologies about that. Could you update to the latest docker version and try again?

See this issue for more details: https://github.com/hms-dbmi/higlass/issues/211

**Comment by rdacemel** [comment]
My apologies as well, that solution worked perfectly, I should have spotted the other post. Thanks a lot for the quick reply.
