### ISSUE TITLE
Label position does not update on window resize

### ISSUE THREAD

**Issue by flekschas** [hms-dbmi/higlass#225]
_Commit_: Develop

#### Steps to reproduce
1. Resize the browser window

#### Observed behavior
![feb-27-2018 14-42-36](https://user-images.githubusercontent.com/932103/36751047-08a6641a-1bcd-11e8-98eb-40e88c800a23.gif)

#### Expected behavior
Label position should update

**Comment by pkerpedjiev** [comment]
Fixed in v1.0.0-alpha.3
