### ISSUE TITLE
chromosome coordinates appear to start at 0

### ISSUE THREAD

**Issue by ngehlenborg** [hms-dbmi/higlass#23]
_Commit_: ?

#### Steps to reproduce
1. zoom into chromosome axis/grid until individual positions are shown

#### Observed behavior
- the first position of chromosome `n` appears to be 0 rather than 1.

![image](https://cloud.githubusercontent.com/assets/1216518/22589240/51989536-e9d7-11e6-9c04-8b1dd42aa725.png)

#### Expected behavior
- the positions should be shifted 1 unit to the left and the first position of a new chromosome should be mapped to the grid axis

**Comment by pkerpedjiev** [comment]
Fixed in local version. Will close the bug when the changes are pushed to the public repo:

![image](https://cloud.githubusercontent.com/assets/2143629/22594449/22af7f04-e9f1-11e6-967a-d7782eb99c34.png)
