### ISSUE TITLE
Build/package a 'hglib.min.js' & 'hglib.js' (development version) side-by-side

### ISSUE THREAD

**Issue by alexkb0009** [hms-dbmi/higlass#230]
At the moment, the default import file from `higlass` NPM library is minified. e.g.  `import createHgComponent, { HiGlassComponent, ... } from 'higlass'`.

Propose to *not* minimize/compress the default-imported 'hglib.js', and to instead add a 'hglib.min.js' file next to it in the /dist/scripts/ & /build/ directories.

Reasoning is that when importing the component via `import` statement, most of the time people would run their own cycle of webpack or babel to generate a final JS bundle.
In this case there is no reason to have the imported file be minified (is harder to debug, especially on otherwise NODE_ENV=development webpack builds), and the minified file adds to time of (re-)minimizing JS output file through webpack 'UglifyJS' plugin.

Minified version should also still be available for loading directly into browsers.

**Comment by flekschas** [comment]
@pkerpedjiev We could add https://github.com/leftstick/unminified-webpack-plugin to the build process. It seems to work just fine (tested it locally)

**Comment by pkerpedjiev** [comment]
Will be implemented in `1.2.4`.
