### ISSUE TITLE
View header bar should hold some tooltips

### ISSUE THREAD

**Issue by flekschas** [hms-dbmi/higlass#234]
_Commit_: http://higlass.io

Imagine being a forgetful user like I who is not sure what each icon in the view header bar is good for. A tooltip would be greatly appreciated. 😍

#### Steps to reproduce
1. Hover over an icon in the View header bar

#### Observed behavior
- Nothing happens

#### Expected behavior
- A tooltip should appear eventually

**Comment by pkerpedjiev** [comment]
Added in the develop branch using `title` tags.
