### ISSUE TITLE
Line track tool tip is causing scrollbar madness

### ISSUE THREAD

**Issue by flekschas** [hms-dbmi/higlass#236]
_Commit_: develop

#### Steps to reproduce
0. Use a non-touch mouse or activate scrollbars
1. Open one of the full screen demos
2. Mouse around a corner
3. Enjoy the scrollbar appearance-disappearance madness

#### Observed behavior
- It's beautiful! Check it out.

![apr-16-2018 20-38-05](https://user-images.githubusercontent.com/932103/38842177-8435727e-41b6-11e8-9725-a0ad80f531b1.gif)

#### Expected behavior
- Although it's nice, the tool tip should not appear appear on default or at least after some delay.

**Comment by pkerpedjiev** [comment]
Fixed in the develop branch by setting the mouseover labels to `fixed`
