### ISSUE TITLE
all interactions broken on Safari

### ISSUE THREAD

**Issue by ngehlenborg** [hms-dbmi/higlass#25]
_Commit_: ?

#### Steps to reproduce
1. Load in Safari Version 10.0.2 (12602.3.12.0.1)
2. Click on default map.

#### Observed behavior
- Unable to move map or zoom.
- Console error: 
![image](https://cloud.githubusercontent.com/assets/1216518/22593825/70af466a-e9ee-11e6-8e52-26cc22652c25.png)

#### Expected behavior
- No error when trying to move the map or zoom in.

**Comment by pkerpedjiev** [comment]
Fixed in v0.4.39 (and probably earlier) by Fritz.
