### ISSUE TITLE
Hitting enter in track selection dialog triggers a URL location change

### ISSUE THREAD

**Issue by flekschas** [hms-dbmi/higlass#250]
_Commit_: http://higlass.io

#### Steps to reproduce
1. Open http://higlass.io/app/?config=CemjYypdRgWC9dBP_Bctqw
2. Add a track track via the cog wheel icon
3. Search for a name (e.g., `gene`) and hit `ENTER`

#### Observed behavior
- Page redirects to `http://higlass.io/app/?`

![apr-29-2018 21-30-49](https://user-images.githubusercontent.com/932103/39413208-0fdd0fd8-4bf5-11e8-83a9-dd642a720e55.gif)

#### Expected behavior
- The first found track should be selected or at least _nothing_ should happen.
- This current behavior makes no sense and is super annoying as the current view config is lost

**Comment by pkerpedjiev** [comment]
Fixed in develop branch.
