### ISSUE TITLE
Adjusting view port projection brakes view linking / synchronization

### ISSUE THREAD

**Issue by flekschas** [hms-dbmi/higlass#251]
_Commit_: http://higlass.io/app/?config=DT_obkifRi6Xx_TnF3iFXA

#### Steps to reproduce
1. Open http://higlass.io/app/?config=DT_obkifRi6Xx_TnF3iFXA
2. Change the view port in the second view on the left
3. Link / synchronization to other views of this view is broken

#### Observed behavior
- Link / synchronization to other views of this view is broken

![apr-29-2018 22-09-13](https://user-images.githubusercontent.com/932103/39413563-06704762-4bfa-11e8-9052-05b64eca48fc.gif)

#### Expected behavior
- Something more predictable

**Comment by pkerpedjiev** [comment]
Fixed.

See also https://github.com/hms-dbmi/higlass/issues/79.
