### ISSUE TITLE
New gene track doesn't like zoom outs

### ISSUE THREAD

**Issue by flekschas** [hms-dbmi/higlass#252]
_Commit_: latest dev branch

#### Steps to reproduce
1. open http://localhost:8080/
2. zoom ou

#### Observed behavior
![may-02-2018 13-45-46](https://user-images.githubusercontent.com/932103/39540005-66e797f0-4e0f-11e8-818d-afdb1864c9c6.gif)

#### Expected behavior
- Mhh this shouldn't happen?

**Comment by pkerpedjiev** [comment]
Need to zoom out quickly and then zoom back in to reproduce this.

Should be fixed in v1.0.0-alpha.11.
