### ISSUE TITLE
Matrix Labels broken

### ISSUE THREAD

**Issue by flekschas** [hms-dbmi/higlass#253]
_Commit_: dev branch

#### Steps to reproduce
1. Open http://localhost:8080/

#### Observed behavior
![labs](https://user-images.githubusercontent.com/932103/39540181-e0e2525c-4e0f-11e8-8ee2-52db062fe2a0.gif)

#### Expected behavior
- labels should always be visualized properly

**Comment by pkerpedjiev** [comment]
As far as I can tell, this is fixed in v1.0.0-alpha.7.
