### ISSUE TITLE
New matrix cursor tool tip causes scrollbar appearance

### ISSUE THREAD

**Issue by flekschas** [hms-dbmi/higlass#254]
_Commit_: dev branch

#### Steps to reproduce
1. Open http://localhost:8080/
2. Mouse around at the bottom of your view

#### Observed behavior
![label-madness](https://user-images.githubusercontent.com/932103/39541054-8f8701f2-4e12-11e8-87f4-2dc397170744.gif)

#### Expected behavior
- Shouldn't happen

**Comment by pkerpedjiev** [comment]
What browser are you using?

**Comment by pkerpedjiev** [comment]
Should be fixed in v1.0.0-alpha.11
