### ISSUE TITLE
Tracks in dialog window should be sorted alphabetically

### ISSUE THREAD

**Issue by flekschas** [hms-dbmi/higlass#256]
_Commit_: higlass.io

#### Steps to reproduce
1. add a track
2. search for `gene`

#### Observed behavior
![screen shot 2018-05-06 at 5 54 14 pm](https://user-images.githubusercontent.com/932103/39678230-a3978daa-5156-11e8-8d5c-5caf12c15d63.png)

The order seems to be random? 

#### Expected behavior
- Alphabetically ordered

**Comment by pkerpedjiev** [comment]
Fixed in `>=1.2.4`.
