### ISSUE TITLE
Zoom events do not trigger from location of mouse pointer

### ISSUE THREAD

**Issue by alexpreynolds** [hms-dbmi/higlass#257]
_Commit_: v0.6.21 of higlass-website, v1.6.0 of higlass-server

#### Steps to reproduce

Built Docker container from Dockerfile in higlass-develop-docker and deployed to EC2 instance. Viewed EC2 instance in Chrome v65.0.3325.181.

#### Observed behavior

Here is a video clip showing the issue:

https://youtu.be/fjGWNfagiUk

The mouse pointer starts on the single-view section and scrolling works as expected, triggering a zoom event on the single-view section. 

At around 0:12, I scroll down the demo page to the two-linked-view section and move the mouse pointer over either of these two views. 

When I start a zoom event over this view, the display of the single-view matrix is changed, not the views in the two-linked-view section.

Likewise, at around 0:27, I move the mouse pointer over the continuous signal ("genome browser") view and start a zoom event there, which changes the single-view matrix.

#### Expected behavior

I was thinking that scrolling should trigger a zoom event where the mouse pointer is located, similar to how the higlass.io demo page works.

**Comment by flekschas** [comment]
Thanks for including the video! This is definitely a bug related to an upcoming new version which needs some more bug fixing.

@pkerpedjiev It's probably a issue with CSS or maybe an ID clash

**Comment by pkerpedjiev** [comment]
Should be fixed in v1.0.0-alpha.7.
