### ISSUE TITLE
Mouseenter events on 1D signal tracks leave dots

### ISSUE THREAD

**Issue by alexpreynolds** [hms-dbmi/higlass#258]
_Commit_: v0.6.21 of higlass-website, v1.6.0 of higlass-server

#### Steps to reproduce

Built Docker container from Dockerfile in higlass-develop-docker and deployed to EC2 instance. Viewed EC2 instance in Chrome v65.0.3325.181.

#### Observed behavior

Here is a video clip showing the issue:

https://youtu.be/q-83owUHULc

The mouse pointer starts on the 1D continuous signal ("genome browser") view and is moved over the tracks. At about 0:05 there is a trail of dots left on signal tracks, where the mouse pointer had entered the track and left.

#### Expected behavior

I was thinking that this dot would be removed after the mouse pointer leaves the track.

**Comment by pkerpedjiev** [comment]
Should be fixed in `v1.0.0-alpha.7` higlass library and in the upcoming `v0.4.1` higlass-docker version.
