### ISSUE TITLE
Make adding top and bottom track more affordable

### ISSUE THREAD

**Issue by flekschas** [hms-dbmi/higlass#260]
_Commit_: higlass.io

#### Steps to reproduce
1. When clicking on `plus`

#### Observed behavior
<img width="244" alt="screen shot 2018-05-08 at 4 39 39 pm" src="https://user-images.githubusercontent.com/932103/39781935-9631ef46-52de-11e8-9869-939361c16694.png">

#### Expected behavior
- The top and bottom buttons are much smaller than the left, right an center.
- The top and bottom buttons should be a bit bigger

**Comment by pkerpedjiev** [comment]
Is this better?

![image](https://user-images.githubusercontent.com/2143629/45765709-b3119d80-bc03-11e8-814a-19ecd1a3b634.png)

**Comment by flekschas** [comment]
Much better!

**Comment by pkerpedjiev** [comment]
OK, will be in the next releaese.
