### ISSUE TITLE
SVG export may be missing multivec track

### ISSUE THREAD

**Issue by alexpreynolds** [hms-dbmi/higlass#266]
_Commit_: v0.6.26 of higlass-website, v1.6.3 of higlass-server, v1.0.0-alpha.12 of higlass

#### Steps to reproduce
1. Configure view with desired track and view parameters (example case: gene annotations and multivec track)
2. Export SVG from configuration menu
3. Open SVG in Adobe Illustrator

#### Observed behavior
- The SVG output contains gene annotations but seems to lack the multivec track
- There is a layer in the SVG with space for the multivec primitives, but it appears empty

https://youtu.be/pVR6u_Wd25w

#### Expected behavior
- The SVG output contains gene annotations and multivec track

**Comment by flekschas** [comment]
Thanks for pointing that out.

@daniellenguyen can you check?

**Comment by pkerpedjiev** [comment]
Should be fixed in v0.2.0-alpha.2.
