### ISSUE TITLE
Dot displayed at cursor location

### ISSUE THREAD

**Issue by flekschas** [hms-dbmi/higlass#268]
_Commit_: higlass.io

#### Steps to reproduce
1. Mouse over a line graph

#### Observed behavior
![dot-at-cursor](https://user-images.githubusercontent.com/932103/41388322-6bf12fd4-6f59-11e8-8258-accccf7017d8.gif)

#### Expected behavior
In the gif it looks fine but I am wondering what this is good for as the mouse cursor always points to the location of the dot anyway and is at most 12px or so off

**Comment by pkerpedjiev** [comment]
Should be fixed in `v1.2.4`

**Comment by pkerpedjiev** [comment]
Oops, wrong issue.

**Comment by pkerpedjiev** [comment]
I think this is generally good because it gives the user an indication of which y-value is being hovered over.

![image](https://user-images.githubusercontent.com/2143629/45692757-8e48f780-bb29-11e8-9a60-955c7499ae97.png)

And it's off by default now.
