### ISSUE TITLE
zoomToDataExtend is broken

### ISSUE THREAD

**Issue by flekschas** [hms-dbmi/higlass#288]
_Commit_: current dev branch

#### Steps to reproduce
1. Call `hgApi.zoomToDataExtend()`

#### Observed behavior
- The viewport will be reset to the initial x and y domain

#### Expected behavior
- The viewport should be set such that all of the data is visible

![jul-26-2018 14-34-32](https://user-images.githubusercontent.com/932103/43281186-0b936d60-90e1-11e8-9a5b-8e99b82b74c5.gif)

**Comment by pkerpedjiev** [comment]
Should be fixed in `v1.2.0`.
