### ISSUE TITLE
Mouse tracking problems with non-default background

### ISSUE THREAD

**Issue by alexpreynolds** [hms-dbmi/higlass#301]
_Commit_: 

Tag v0.6.31 of higlass-website
Master branch of higlass-server
Tag v0.9.1 of clodius

#### Steps to reproduce
1. Add multivec track, rendered as type "horizontal-stacked-bar"
2. Set the background track color to "black" in JSON configuration object
3. Move mouse pointer over stacked bar elements

#### Observed behavior
- Mouse tracking does not show correct data values in the overlay window:

![tracking-test-black](https://user-images.githubusercontent.com/33584/43733936-1896ab84-996b-11e8-8090-b9a8f6b2d73f.gif)

- Additionally, switching the track background color from black to white does not refresh the background color

#### Expected behavior
- Mouse tracking appears to be correct when the white or default track background color is set in the JSON configuration object:

![tracking-test-white](https://user-images.githubusercontent.com/33584/43734222-e5fdaf1e-996b-11e8-8434-f323e54ef04a.gif)

If the original track background color was black and switched to white, even though the track background color stays black, the tracking works correctly (as if the background was white).

Edit: This effect is visible from the default configuration loaded via our local server: http://hg-dev.altius.org/app

It is also visible from the test configuration available via higlass.io: http://higlass.io/app/?config=L4nKi6eGSzWOpi-rU2DAMA

**Comment by pkerpedjiev** [comment]
Should be fixed in `v0.2.0-alpha.3`. 

See here: http://higlass.io/app/?config=WWw2GmdZSN-z6r8_4vUwkA
