### ISSUE TITLE
Line track inverted at small heights / widths

### ISSUE THREAD

**Issue by flekschas** [hms-dbmi/higlass#302]
_Commit_: Latest dev

#### Steps to reproduce
1. Set the height or width of a horizontal or vertical line track to `6`
2. manually increase the height of the track

#### Observed behavior
- The track is initially drawn inverse because the baseline seems to be incorrectly set too high

![inverted-line](https://user-images.githubusercontent.com/932103/43856839-a1bca776-9b17-11e8-8822-e892ba75ab23.gif)

Figure: focus on the tip of the large peak. As I increase the height, the tip of the peak does not move. It seems like there's some kind of top and bottom padding and then the total track height is smaller than the combined padding the high and low positions are inverted. For example, highest value's y position is track height (6) - top margin (4) = 2 while the lowest value is 0 + bottom margin (4) = 4. Maybe this is what's happening?

#### Expected behavior
- This should never happen

**Comment by pkerpedjiev** [comment]
That's exactly what was happening. Should be fixed in v1.2.4.
