### ISSUE TITLE
Vertical scroll bar

### ISSUE THREAD

**Issue by flekschas** [hms-dbmi/higlass#31]
_Commit_: 2274226ff8958ebf560bd1d558fded5632ea2c5f

#### Steps to reproduce
1. Open HiGlass

#### Observed behavior
- There is a vertical scroll bar of ~10px

![bildschirmfoto 2017-02-05 um 15 31 31](https://cloud.githubusercontent.com/assets/932103/22629660/35f69ff2-ebb8-11e6-83c6-33dd2f14f21d.png)

#### Expected behavior
- This scroll bar should not be there, i.e., the main container shouldn't overflow.

**Comment by flekschas** [comment]
PS: This scroll bar is unrelated to the style updates of `flekschas/style-header-and-menu`

**Comment by pkerpedjiev** [comment]
Should be fixed in more recent releases. Reopen if you notice this again.
