### ISSUE TITLE
Gene annotations and labels move on configuration change

### ISSUE THREAD

**Issue by alexpreynolds** [hms-dbmi/higlass#317]
_Commit_: 

higlass-manage 0.1.13

#### Steps to reproduce
1. Add hg38 gene annotation track
2. Right-click on track (or click on gear icon)
3. Select: *Configure Series > Label Position* and select any option

#### Observed behavior
- Gene annotation body will shift leftwards to a different genomic region; and/or,
- Label position "hugs" the top of the annotation body more closely

Also, the label position setting does not change the actual label position. The label always stays aligned to the top-middle of the annotation body.

#### Expected behavior
- Gene annotation position should not shift 
- Label is positioned by setting.

**Comment by pkerpedjiev** [comment]
I'm not sure I see this behavior. Is this what you were doing?

![aug-21-2018 09-36-50](https://user-images.githubusercontent.com/2143629/44404861-e5a57900-a525-11e8-8936-96825f609818.gif)

**Comment by alexpreynolds** [comment]
Here is the view configuration I am testing, if useful: 

http://hg-dev-rev2.altius.org/app/?config=c7i2jaqkRyu3vgpys61r_w

**Comment by pkerpedjiev** [comment]
Wonderful, thank you! I reproduced it in my local environment and added a test. Should have a fix in the next few days.

**Comment by pkerpedjiev** [comment]
Should be fixed in the latest release.
