### ISSUE TITLE
SVG export contains black layer in background of gene and chromosome tracks

### ISSUE THREAD

**Issue by alexpreynolds** [hms-dbmi/higlass#322]
_Commit_: 

* Master branch of higlass
* Compiled version of Danielle's higlass-multivec
* Compiled version of master branch of higlass-website
* Master branch of higlass-server

#### Steps to reproduce
1. Add hg38 gene annotations and chromosome tracks
2. Scroll to any spot
3. Export views as SVG

#### Observed behavior
- Gene and chromosome tracks contain a layer with a black background

Here is a snapshot of what the SVG looks like in Adobe Illustrator CC 22.1:

<img width="1920" alt="hgadobeillustratorsvgtest" src="https://user-images.githubusercontent.com/33584/44949547-dad1ca80-ade8-11e8-93c7-1e75006c0404.png">

Notice the selected layer in the Layers palette and the selected `rect` (or `g`? — perhaps not as it is labeled as a Path element in Adobe...) element in the SVG. 

To view this in a browser, here is a test URL:

http://explorer.altius.org/app/?config=ObkyhPvST7KdrO9J9PNk-g

This test viewconf contains viewport projections; however, closing those viewports to remove them does not change how the SVG is rendered (the track background layers are still rendered black in the SVG).

#### Expected behavior
- Tracks contain the configured background (white or transparent, if default or not specified in JSON view object)

**Comment by alexpreynolds** [comment]
Here's a stripped-down viewconf:

http://explorer.altius.org/app/?config=UC-0VxJgSFyvBYbJDnmRJQ

The resulting SVG uses a transparent fill on the two `rect` elements used for the chromosome and gene annotations. 

For example, here's the first `rect`:

```
<svg
    xmlns:xlink="http://www.w3.org/1999/xlink"
    xmlns="http://www.w3.org/2000/svg">
    <g>
        <g class="g-labels" style="clip-path:url(#MDG-JZS-Sn2oHrLzO1p7cA);">
            <rect x="15" y="77" width="1187" height="55" fill="transparent"></rect>
            ...
</svg>
```

Manually changing this from `transparent` to `white` fixes the rendering in Illustrator and Inkscape.

As to why this happens, according to the SVG specification, the default fill color assignment is `black` (https://www.w3.org/TR/SVG11/painting.html#SpecifyingPaint). If `transparent` is not a valid color keyword (https://www.w3.org/TR/SVG11/types.html#ColorKeywords), then that might explain why the fill color is black. 

This doesn't appear to affect stroke properties (https://www.w3.org/TR/SVG11/painting.html#StrokeProperties).

If the keyword `transparent` is used as a fill color for other elements, this may happen there, when rendering to SVG.

Another property for specifying transparency or alpha that might instead be useful is `fill-opacity` (https://www.w3.org/TR/SVG11/painting.html#FillOpacityProperty).

**Comment by flekschas** [comment]
@alexpreynolds is this still an issue? I can't seem to reproduce the issue in Affinity Designer or Gapplin (both running on macOS 10.12.6).

**Comment by alexpreynolds** [comment]
It is for me, albeit with a locally built server/client/multivec plug setup that may not be in sync with whatever is current on higlass.io. You might try using Inkscape (free, requires separate Xquartz install) or a demo copy of Adobe Illustrator, if you don't have a license. If you have a link to your viewconf, I can test it out too. 

I suspect the issue is that `transparent` should not be used as a fill color in the SVG output, ultimately.  It may not be treated as a valid color keyword, and so may get ignored by SVG renderers that follow spec and replace it with the default (black).

**Comment by flekschas** [comment]
I downloaded it from the link you provided so it's unrelated to higlass.io but you're right `fill="transparent"` is nonsense. I'll try to fix it

**Comment by flekschas** [comment]
@alexpreynolds Fixed in develop. Will be part of `v1.2.4`

**Comment by alexpreynolds** [comment]
Cool! Do you know when that might be coming down the pipe?

**Comment by flekschas** [comment]
Should be released soonish. Unless @pkerpedjiev has some more things we could just publish `v1.2.4` of the client. Regarding the whole suite, I think we're just trying to harden the new `v1.2` branch which comes with quite a few new additions but it shouldn't take much longer.
