### ISSUE TITLE
Cooler format support

### ISSUE THREAD

**Issue by joachimwolff** [hms-dbmi/higlass#324]
Hi,

I am the developer of the Hi-C data analysis software HiCExplorer (https://github.com/deeptools/hicexplorer) and some of my user like your tool for interactively exploring the data. We support as output the cool file format as you do it for the input, but in the most cases our cool matrices are not accepted by HiGlass. I think the main issue here is that the cooler documentation is not complete and that there is no clear standard how to handle the data. To improve user satisfaction, I have the following questions:

1. Do you support only integer for the column 'counts'? How do you handle floats?
2. Do you check for and if yes, do you apply the correction factors stored in the optional column 'weights'?
3. How do you handle cases like converted matrices from hic2cool which is ignoring the column 'weights' and stores its correction factors in the three additional columns 'KV', 'VC' and 'VC_SQRT'? 
4. How do you handle multi-cooler file format? There is no clear standard set how the path should look like. E.g. a mcool file created with CLI cooler tools is having paths like `:/1`, `:/2` and at the same time files produced by hic2cool uses `:/resolutions/10000` etc.

One issue with question 1. is that, imho, it doesn't make sense to store the counts as integers. After a correction is applied, the values are floats in the most cases. In theory it is possible to restore the correction with the correction factors but practice shows, that this is not 100% accurate. We have here issues that some of our analysis tools compute different results caused by these inaccuracies. The answer of the cooler people was to change the data type of 'counts' to float. And this is causing issues with other tools which expect integers... Long story short: It would be nice to come to some agreement how software reads and accepts cooler files.

Best,

Joachim

**Comment by pkerpedjiev** [comment]
Hi Joachim, it's great to hear that you want to add support for HiGlass and I'm sorry it's proving challenging. I can try to answer the questions as best as I can but I think @nvictus can add some perspective as well:

> 1. Do you support only integer for the column 'counts'? How do you handle floats?

@nvictus this one's for you. 

> 2. Do you check for and if yes, do you apply the correction factors stored in the optional column 'weights'?

Yes. If there's a `weights` column, we use that and provide the option to use other columns as balancing factors. Those can be selected in the heatmap options menu:

![image](https://user-images.githubusercontent.com/2143629/45761011-63c66f80-bbf9-11e8-8a42-999c7a208992.png)

> 3. How do you handle cases like converted matrices from hic2cool which is ignoring the column 'weights' and stores its correction factors in the three additional columns 'KV', 'VC' and 'VC_SQRT'?

We check if those columns are present. `weights` is the default column for a data transform. We also check for KR, VC, and VC_SQRT. If those are present then we provide options for using them in the menu above. In case you're interested, the server-side code for checking that is located here: https://github.com/pkerpedjiev/hgtiles/blob/817f74873889f3388449349d68bbe2e786e23ff6/hgtiles/cooler.py#L419

> 4. How do you handle multi-cooler file format? There is no clear standard set how the path should look like. E.g. a mcool file created with CLI cooler tools is having paths like :/1, :/2 and at the same time files produced by hic2cool uses :/resolutions/10000 etc.

So this is a bit of an anachronism. We originally used the `:/1`, `:/2` format to indicate powers of 2 resolutions. So the lowest resolution (usually around 16Mb) would be `:/0`, the second lowest would be `:/1` and it would twice the resolution of the lowest and so on until the highest (:/{max-zoom}). As we progressed, we realized that resolutions wouldn't always come in powers of two. We could have 1000, 2500, 5000, 10000, etc... So started using the latter format (`:/resolutions/10000`). Nowadays we support both. You should probably use the `:/resolutions/10000`. It's a lot more flexible.

Hope that helps!

**Comment by joachimwolff** [comment]
Thanks a lot for your answer, the most is used as I thought it is. I will add an enforce option for integers, maybe that will solve the issue of this incompatibility.
One more point I want to clearify: Is it `weight` or `weights`? (With the plural `s`?) Cooler documentation uses it in the singular form,  was this here just a typo or do you expect the name `weights`?

**Comment by nvictus** [comment]
Hi Joachim,

1. HiGlass handles integer or floating point `count` columns. In the end, data ends up getting cast to float with a simple numpy cast and b64 encoded before being sent off to the client.

2. `weight` was the name reserved as the default target column for `cooler balance`. We apply iterative correction with different defaults than KR, notably a scale normalization to make marginals sum to unity. 

3. The original multicool format was :/1, :/2, but we are transitioning completely to the :/resolutions/
convention. This will become the default in the next major release of cooler. Right now, it kicks in only when asking for explicit resolutions with the `-r` option in `cooler zoomify`.

4. I am very curious about what problems you are encountering with changing the dtype of the `count` column and how we might be able to help. We've been trying to make it easier to create coolers with custom dtypes and even multiple value columns.

**Comment by joachimwolff** [comment]
Hi,

Thanks for your answers, it was helpful for me.

Sorry for the delayed answer. I think I have the reason why cooler import for HiGlass not working as expected: Could it be that you do not support 'regular' cooler files i.e. if the data is written to root and not to '/resolutions/1000'?

I tested today your latest docker container. If I try to open regular cooler files with the data in root, HiGlass tells me it is loading, but nothing more happens. As soon as I create out of the identical file a multicooler file it is working.

Can you confirm this?


Concerning 4. of @nvictus answer: I solved it now, the issue was I changed the datatype via `cooler._writer.COUNT_DTYPE = np.int32` but I think you changed the behaviour. Using a dict for the parameter `dtype` for `cooler.io.create` with the column names and the data type made it work.

Best,

Joachim

**Comment by pkerpedjiev** [comment]
> Could it be that you do not support 'regular' cooler files i.e. if the data is written to root and not to '/resolutions/1000'?

Yes, that is indeed correct. HiGlass requires multiple resolutions for its zooming functionality. Otherwise the browser would be overwhelmed if it had to load the entire high resolution cooler.
