### ISSUE TITLE
UI won't work if data referenced by config is missing

### ISSUE THREAD

**Issue by mccalluc** [hms-dbmi/higlass#38]
_Commit_: 
SERVER_VERSION: 0.2.4
WEBSITE_VERSION: 0.5.0

#### Steps to reproduce
1. Bring up a docker container
2. Go to the app
3. Click in the upper right to try to add a track 

#### Observed behavior
Javascript is erroring out because it can't load the data referenced in the default config.

#### Expected behavior
- Perhaps make it more robust in the face of missing data?
- Or, if we keep this constraint, make it clear in the readme how to zero out the default config, or consider shipping with an empty config.

**Comment by ngehlenborg** [comment]
> Perhaps make it more robust in the face of missing data?

That's the way to go. This will be happening all the time and should result in warnings, not errors.

**Comment by mccalluc** [comment]
If I hit this:
- http://localhost:8888/app/?config=my-view-conf

It looks for:
- http://localhost:8888/api/v1/viewconfs/?d=my-view-conf

and returns with a 500. So if I can figure out how to load an empty viewconf, I could add that step to the docker instructions, and folks would be able to start it up locally.

**Comment by flekschas** [comment]
Related to #36

**Comment by mccalluc** [comment]
@pkerpedjiev : I can not reproduce this. Instead, If I supply a bad tilesetUid, I get the message "Tileset info not found", and I can add a new track through the UI. Unless you think this is not really fixed, please close?

**Comment by pkerpedjiev** [comment]
Fixed.
