### ISSUE TITLE
track menu icons are swapped

### ISSUE THREAD

**Issue by ngehlenborg** [hms-dbmi/higlass#43]
_Commit_: 

#### Steps to reproduce
1. Hover over track to get track menu

#### Observed behavior
- "settings" icon is used instead of "close" icon and vice versa

![image](https://cloud.githubusercontent.com/assets/1216518/23171914/0ac2ef2c-f822-11e6-8553-4b70448e43f8.png)

#### Expected behavior
- Correct icons.

**Comment by pkerpedjiev** [comment]
Fixed in `hotfix-0.3.39 branch`:

![image](https://cloud.githubusercontent.com/assets/2143629/23173131/6f0a0692-f858-11e6-80df-9c20a3085b4a.png)

**Comment by pkerpedjiev** [comment]
Fixed on higlass.io
