### ISSUE TITLE
FF: Controls roundrect is empty for vertical panes

### ISSUE THREAD

**Issue by mccalluc** [hms-dbmi/higlass#53]
_Commit_: 
SERVER_VERSION: 0.3.4
WEBSITE_VERSION: 0.5.10

#### Steps to reproduce
1. In Firefox, load a vertically oriented pane
2. Hover over it.

#### Observed behavior
The roundrect appears with hover, but it is empty:

<img width="72" alt="screen shot 2017-03-08 at 9 54 29 am" src="https://cloud.githubusercontent.com/assets/730388/23708881/8cc8acd6-03e5-11e7-9de0-fe7509100945.png">

#### Expected behavior
It should work the same as it does on Chrome.

**Comment by pkerpedjiev** [comment]
Appears to be fixed.
