### ISSUE TITLE
Window vertical resize, but HiGlass keeps original height

### ISSUE THREAD

**Issue by mccalluc** [hms-dbmi/higlass#58]
_Commit_: 
SERVER_VERSION: 0.3.4
WEBSITE_VERSION: 0.5.10

#### Steps to reproduce
1. Resize the browser window horizontally --> HiGlass redraws to use the appropriate width
2. Resize the browser window vertically --> HiGlass does not redraw with the appropriate height: It retains the original.

#### Expected behavior
This isn't totally unreasonable, but I wanted to point it out.

**Comment by pkerpedjiev** [comment]
The lack of a resize handle in the bottom right corner indicates that the view extends beyond the bottom of the browser. This shouldn't happen. The HiGlassComponent should never extend beyond the browser window bounds.

![mar-08-2017 17-23-51](https://cloud.githubusercontent.com/assets/2143629/23726911/092e0ea4-0424-11e7-95c1-65af2d38ae39.gif)

**Comment by pkerpedjiev** [comment]
Not anymore.
