### ISSUE TITLE
Resizing pane does not change coordinates used as basis for duplicate

### ISSUE THREAD

**Issue by mccalluc** [hms-dbmi/higlass#62]
_Commit_: 
SERVER_VERSION: 0.3.4
WEBSITE_VERSION: 0.5.10

#### Steps to reproduce
1. Load a center pane
2. Shrink the width by half
3. Hit duplicate

#### Observed behavior
- The new pane will not be identical to the old: instead it will cover the same address range as the old one did before shrinking, but since it has less space, the zoom levels on the two panes will not match. (And the dynamic color rescaling may make it harder to realize they are both looking at the same data.)

#### Expected behavior
- Duplicated panes should be identical to the original.

**Comment by pkerpedjiev** [comment]
Similiar to: https://github.com/hms-dbmi/higlass/issues/62

Should be fixed in `>=1.2.4`.
