### ISSUE TITLE
Pick the assembly that the genome position search box works with

### ISSUE THREAD

**Issue by pkerpedjiev** [hms-dbmi/higlass#64]
The genome position search box requires an assembly (chromSizes) to show the current position. It also requires a set of gene annotations to support autocomplete. It should be possible to somehow select these in the UI.

**Comment by rdacemel** [comment]
It would be indeed really nice to search for a position in customized genomes given with homemade chromSizes files, I don't think it is possible now. BTW, thanks for making it possible to put customized axis! Keep it up, love this brower :)

**Comment by pkerpedjiev** [comment]
If you import the customized genome with the `--coordSystem` attribute, you can now select it from the assembly dropdown.
