### ISSUE TITLE
Should it be easier to exit from menu selection?

### ISSUE THREAD

**Issue by mccalluc** [hms-dbmi/higlass#66]
_Commit_: 
SERVER_VERSION: 0.3.4
WEBSITE_VERSION: 0.5.10

#### Steps to reproduce
1. Click on the gear to bring up the menu on a track, and then imagine you wanted to exit the menu without making a selection

#### Observed behavior
- Neither clicking off the menu (which would close a normal pull-down) nor hitting escape (which would exit a modal) does anything. 

#### Expected behavior
- Either clicking off-menu or hitting escape should close it.

**Comment by pkerpedjiev** [comment]
Clicking off the menu closes it now.
