### ISSUE TITLE
Inter-view operations not working on Firefox

### ISSUE THREAD

**Issue by mccalluc** [hms-dbmi/higlass#67]
_Commit_: 
SERVER_VERSION: 0.3.4
WEBSITE_VERSION: 0.5.10

#### Steps to reproduce
On Firefox:
1. Add dataset
2. Duplicate
3. Select "Take zoom from" on the top one

#### Observed behavior
Note that the bottom view is highlighted with green, and if you move the mouse down, it looks like you can put the green highlight on the area below the view.

#### Expected behavior
On chrome, the green is initially positioned on the top view. It feels like an off-by-one bug in Firefox. I have not see any of the view-linking operations work in FF, but that could just be this superficial issue, and not anything deeper.

**Comment by pkerpedjiev** [comment]
Works now.
