### ISSUE TITLE
`gulp serve` doesn't work... no gulpfile

### ISSUE THREAD

**Issue by mccalluc** [hms-dbmi/higlass#7]
_Commit_: d58ce79b27d2d4b32431d05a84ce88b66ec749b7

#### Steps to reproduce
- checkout
- npm install
- npm install gulp --global
- gulp serve

#### Observed behavior
No gulpfile found

#### Expected behavior
Server start?

**Comment by pkerpedjiev** [comment]
We don't use gulp files any more at all.
