### ISSUE TITLE
Multi-views layout corrupted by window repeated resizing

### ISSUE THREAD

**Issue by mccalluc** [hms-dbmi/higlass#75]
_Commit_: 
SERVER_VERSION: 0.3.4
WEBSITE_VERSION: 0.5.10

#### Steps to reproduce
This seems to be more of an issue on Chrome than Firefox.
1. Load http://higlass.io/app/?config=YTNBiN7gTU-z-Z0RU24-2g
2. Repeatedly resize the window without giving the re-rendering time to catch up

#### Observed behavior
<img width="1008" alt="screen shot 2017-03-09 at 9 51 31 am" src="https://cloud.githubusercontent.com/assets/730388/23755444/5b71ced2-04ae-11e7-9f5e-e76c94fd0292.png">
<img width="893" alt="screen shot 2017-03-09 at 9 44 46 am" src="https://cloud.githubusercontent.com/assets/730388/23755447/5e8e4046-04ae-11e7-9b54-32fce586cad4.png">

#### Expected behavior
As it redraws, the intermediate states are also messy... Maybe we should assert that intermediate rendering states will be consistent, and then when we're done the final state will be consistent too.

**Comment by mccalluc** [comment]
Besides assuring that intermediate states are consistent, could also:
- Only redraw when things are stable
- Or, just redraw a rectangle for each view, and that's something we could more likely keep up with.

**Comment by pkerpedjiev** [comment]
Should be fixed in more recent releases. At least I haven't seen this type of behavior for a while.
