### ISSUE TITLE
Max zoom not enforced

### ISSUE THREAD

**Issue by mccalluc** [hms-dbmi/higlass#77]
_Commit_: 
SERVER_VERSION: 0.2.6
WEBSITE_VERSION: 0.5.6

#### Steps to reproduce
On the examples page it says "Maintaining a minimum zoom level can be useful to show features which are harder to see at higher resolution," but when I visit http://higlass.io/app/?config=CafCfq2wQtyD_BbBj6HbpA I can zoom in beyond the single basepair level. The viewconf does have `"maxZoom": 22`, but I guess that's not enforced? Is this a regression?

#### Observed behavior
![screen shot 2017-03-09 at 11 03 20 am](https://cloud.githubusercontent.com/assets/730388/23758669/80104d90-04b8-11e7-84ea-f09921f3bfac.png)

#### Expected behavior
The tutorial example for limiting the zoom will have a limited zoom

**Comment by pkerpedjiev** [comment]
It's enforced for the heatmap. Line tracks don't have the max zoom option.
