### ISSUE TITLE
Rendering glich in horizontal diagonal at single-basepair scale

### ISSUE THREAD

**Issue by mccalluc** [hms-dbmi/higlass#78]
_Commit_: 
SERVER_VERSION: 0.2.6
WEBSITE_VERSION: 0.5.6

#### Steps to reproduce
1. Zoom in all the way in on a horizontal diagonal, aiming for a pixel boundary

#### Observed behavior
![screen shot 2017-03-09 at 11 17 27 am](https://cloud.githubusercontent.com/assets/730388/23759339/86196152-04ba-11e7-8424-41fd8996d3c8.png)

#### Expected behavior
The corners of the pixel should lie on the axis

**Comment by pkerpedjiev** [comment]
Looks OK to me in the latest version.
