### ISSUE TITLE
Drag viewport and lose location lock between views

### ISSUE THREAD

**Issue by mccalluc** [hms-dbmi/higlass#79]
_Commit_: 
SERVER_VERSION: 0.3.4
WEBSITE_VERSION: 0.5.10

#### Steps to reproduce
1. Load the mini-views example: http://higlass.io/app/?config=OwPq374bQj6pKQ97iyhXKg
2. Click and drag in the background of any view: note that the viewports remain centered
3. Click and drag one of the grey viewport rectangles: The location lock between it and the new view is lost: Now, instead of moving, the view keep same position, while the viewport moves around.

#### Expected behavior
I guess dragging the viewport does temporarily break the lock between views, but I would expect it to be reestablished once the user lets go of the viewport? I may be thinking about this wrong.

**Comment by pkerpedjiev** [comment]
Will be fixed in `>=1.2.4`
