### ISSUE TITLE
Higlass client empty when acessed from external machine

### ISSUE THREAD

**Issue by dborgesr** [hms-dbmi/higlass#91]
I got the docker higlass container running on a machine and loaded up a few cooler files and it seems to work when accessed from that machine itself, but if I try to access higlass from another machine it just produces a blank square. I think something is wrong with the user permissions or something.

_Commit_: 

#### Steps to reproduce
1.
Load docker on machine, load datasets on machine, and then try to access from a different machine
#### Observed behavior
Blank square where data interface should be

#### Expected behavior
Should be able to observe and manipulate loaded data

**Comment by pkerpedjiev** [comment]
Sorry for the delayed response. This is likely because the django server which serves the data won't accept requests from an unidentified host. To fix this, you need to pass the docker container a `SITE_URL` environment variable:

Example:

```
docker run --detach \
           --publish 8989:80 \
           --volume ~/hg-data:/data \
           --volume ~/tmp:/tmp \
           --name higlass-container \
           --host my.higlass.org \
           gehlenborglab/higlass:v0.0.28
```

**Comment by pkerpedjiev** [comment]
Fixed.
