### ISSUE TITLE
SVG Export

### ISSUE THREAD

**Issue by pkerpedjiev** [hms-dbmi/higlass#97]
HiGlass should offer an option to export views as SVG.

**Comment by pkerpedjiev** [comment]
Added to the view config menu:

![apr-12-2017 16-07-11](https://cloud.githubusercontent.com/assets/2143629/24977168/29740e48-1f9a-11e7-8674-da685a96bcea.gif)

**Comment by gfudenberg** [comment]
export SVG seems to prefer line graphs to bars--
original view:
![image](https://user-images.githubusercontent.com/19657573/32263241-1e865e00-be96-11e7-95a5-c207c0656c12.png)
exported SVG:
![image](https://user-images.githubusercontent.com/19657573/32263250-29da3826-be96-11e7-88ad-e37260f857f0.png)

**Comment by pkerpedjiev** [comment]
Bar export is fixed in higlass `v0.9.9`. I'll post the new docker version before closing this issue.
