### ISSUE TITLE
Custom color map popup broken

### ISSUE THREAD

**Issue by flekschas** [hms-dbmi/higlass#99]
_Commit_:  http://higlass.io/app/?config=Wxxdw3aDTwyyx9TweoxWWQ

#### Steps to reproduce
1. http://higlass.io/app/?config=Wxxdw3aDTwyyx9TweoxWWQ
2. Try to open the custom color map

#### Observed behavior
- Nothing happens 😱

#### Expected behavior
- The color map dialog should open.  😶

**Comment by pkerpedjiev** [comment]
Duplicate of https://github.com/hms-dbmi/higlass/issues/116
